-- Owner: OE
-- Type: TYPE
-- Name: PURCHASEORDER_T
-- Source: plsql_f_ora12c_20260118.out (Lines 686-696)
-- ============================================================

CREATE OR REPLACE EDITIONABLE TYPE "OE"."PURCHASEORDER_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","REFERENCE" VARCHAR2(30 CHAR),"ACTIONS" "ACTIONS_T","REJECTION" "REJECTION_T","REQUESTOR" VARCHAR2(128 CHAR),"USERID" VARCHAR2(10 CHAR),"COST_CENTER" VARCHAR2(4 CHAR),"SHIPPING_INSTRUCTIONS" "SHIPPING_INSTRUCTIONS_T","SPECIAL_INSTRUCTIONS" VARCHAR2(2048 CHAR),"LINEITEMS" "LINEITEMS_T")NOT FINAL INSTANTIABLE
/
/
