-- Owner: OE
-- Type: TYPE
-- Name: SHIPPING_INSTRUCTIONS_T
-- Source: plsql_f_ora12c_20260118.out (Lines 708-719)
-- ============================================================

CREATE OR REPLACE EDITIONABLE TYPE "OE"."SHIPPING_INSTRUCTIONS_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","SHIP_TO_NAME" VARCHAR2(20 CHAR),"SHIP_TO_ADDRESS" VARCHAR2(256 CHAR),"SHIP_TO_PHONE" VARCHAR2(24 CHAR))NOT FINAL INSTANTIABLE
/
/
